clients:
- url: 'http://loki:3100/loki/api/v1/push'

scrape_configs:
 - job_name: fastapi
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      __path__: /var/log/app.log*
