global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'fastapi-app'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-app:5000']

  - job_name: 'node'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-app:9100']
